### ISSUE TITLE
Compare desired and actual versions for preflight check

### ISSUE THREAD

**Issue by puneetguptanitj** [platform9/cctl#113]
Currently we only have a desired version of components in machine's provider config. 
```
      providerConfig:
        ValueFrom: null
        value:
          apiVersion: sshprovider.platform9.com/v1alpha1
          componentVersions:
            cniVersion: v0.6.0
            etcdVersion: v3.3.8
            etcdadmVersion: v0.0.3
            flannelVersion: v0.10.0
            keepalivedVersion: v2.0.4
            kubernetesVersion: 1.10.4
            nodeadmVersion: v0.0.2
```
While checking for version skew we therefore are comparing this "desired" version to the minimum supported upgradable version. However the correct check would be to compare against the actual version. This can be supported by having actual version information as part of machine status. 
This version would be set after machine reconciliation finishes successfully.

platform9/ssh-provider#45
